# Generated by Django 5.1.7 on 2025-03-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('informatique', 'Informatique'), ('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('autres', 'Autres')], max_length=20)),
                ('availability', models.JSONField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('occupancy_rate', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('partially_occupied', 'Partiellement occupée'), ('occupied', 'Occupée')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('level', models.CharField(choices=[('l1', 'L1'), ('l2', 'L2'), ('l3', 'L3'), ('m1', 'M1'), ('m2', 'M2')], max_length=5)),
                ('department', models.CharField(choices=[('informatique', 'Informatique'), ('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('autres', 'Autres')], max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('participants', models.IntegerField(blank=True, null=True)),
                ('proctors', models.ManyToManyField(blank=True, to='exam_scheduler.proctor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_scheduler.room')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_scheduler.exam')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.room')),
            ],
        ),
    ]
